using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        [SerializeField] public SaveVector3 playerPos;
        [SerializeField] public float levelIndex;
        [SerializeField] public int health;
    }
}
